spring:
  datasource:
    url: jdbc:mysql://115.29.175.146:3306/PropertyManagementSystem?useSSL=true
    username: root
    password: qazdzr0403.
#    driver-class-name: com.mysql.jdbc.Driver

    #    #配置德鲁伊数据源
    druid:
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: wall,stat
      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
        wall:
          enabled: true
      # 开启德鲁伊的监控页面
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123455
        reset-enable: false
      #用于采集web-jdbc关联监控的数据
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.css,*.js,*.html,*.jpg,*.png,/druid/*'

      #监控spring bean
      #      aop-patterns: com.*.*.*

      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  #sql映射文件
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# dubbo配置
dubbo:
  application:
    name: base-service
  registry:
    address: zookeeper://47.110.240.165:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 20880
  provider:
    retries: 3